### DISCUSSION TITLE
How to publish .tif via pygeoapi?

### DISCUSSION THREAD

**Discussion by xcomagent95** [geopython/pygeoapi#1027] [Q&A] [answered]
Hello,

i'm trying to publish some data stored as .tif files via the pygeoapi. I'm trying to achieve this with the following provider:

 ```
providers:
          - type: coverage
            name: rasterio
            data: path/to/file
            format:
                name: GTiff
                mimetype: image/tiff  
```
The configuration seems to be valid and the openAPI description can be generated as well. After starting the api i can 
access the coverage metadata, the coverage domain set and the coverage range type but not the coverage data itself. 
I get the following error: `urllib.error.URLError: <urlopen error unknown url type: c>`.

Could someone provide me with some insight as to what the reason for the error could be and maybe provide me with possible solutions.

thanks in advance :)
