### DISCUSSION TITLE
Using rio-tiler as a provider?

### DISCUSSION THREAD

**Discussion by vietnguyengit** [geopython/pygeoapi#1268] [Q&A]
Hi there, I'm just being curious that `rio-tiler`: https://github.com/cogeotiff/rio-tiler at the lower level is a wrapper over `rasterio`; so can I declare `rio-tiler` as a provider when using `pygeoapi` , for example in this doc: https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-coverages.html

```yaml
providers:
    - type: coverage
      name: rasterio
```

to be like

```yaml
providers:
    - type: coverage
      name: rio-tiler
```

or anyhow that I can use rio-tiler with `pygeoapi`?

Thank you
