### DISCUSSION TITLE
Raster (tiff) layer error

### DISCUSSION THREAD

**Discussion by Beemo-afk** [geopython/pygeoapi#1693] [Q&A]
Hi all,

I'm trying to get a raster as a Geotiff into my implementation. However, I keep getting an 'internal server error'.
I've tried the examples from the tutorial ([link here](https://dive.pygeoapi.io/publishing/ogcapi-coverages/)) and from the documentation - and all return the same issue.

I'm using the latest docker image to build the implementation - and for testing have only modified the config file to try use the geotiff.

An extract of the config file is below:

```    
    myRaster:
        type: collection
        title: Test raster  
        description: Test raster (.tiff)  
        providers:
          - type: coverage
            name: rasterio
            data: "/src/test.tiff"
            format:
                name: GTiff
                mimetype: application/tiff
```

I see that another question was asked ([link here](https://github.com/geopython/pygeoapi/discussions/1027)) - and appeared to have worked in the end... so can someone help identify my issue here?
