### DISCUSSION TITLE
Is it possible to use GeoJSON files in a s3 bucket with the GeoJSON provider?

### DISCUSSION THREAD

**Discussion by EHJ-52n** [geopython/pygeoapi#1851] [Q&A]
I am currently trying to serv a GeoJSON file with the GeoJSON provider, which is located in a non-public S3 bucket.

My set-up:

* **pygeoapi version**: v0.19dev aka main
* **resource config**:
  ```yaml
    my-geojson-data-set:
      description: geospatial data of georgia
      extents:
        spatial:
          bbox:
          - 45.196243
          - 41.120975
          - 46.736885
          - 42.115761
          crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        temporal:
          begin: 1970-01-01 00:00:00
          end: 1971-01-01 00:00:00
      keywords:
      - georgia
      - country
      providers:
      - data: s3://my-s3-bucket/path/to/my-data-set.geojson
        id_field: id
        name: GeoJSON
        s3:
          access_key: ***
          anon: false
          endpoint_url: https://obs.eu-de.otc.t-systems.com
          region_name: eu-de
          requester_pays: false
          secret_key: ***
        options:
          s3:
            access_key: ***
            anon: false
            endpoint_url: https://obs.eu-de.otc.t-systems.com
            region_name: eu-de
            requester_pays: false
            secret_key: ***
        type: feature
      title: my-geodata-from-georgia
      type: collection
  ```
  The **s3 credentials** are provided using environment variables:
  
  * `FSSPEC_S3_ENDPOINT_URL`: `https://obs.eu-de.otc.t-systems.com`
  * `FSSPEC_S3_KEY`: `***`
  * `FSSPEC_S3_SECRET`: `***`
  
When trying to access the items in the dataset, I receive the following error message:
  
```
[...]
[2024-11-19T15:59:32Z] {/pygeoapi/pygeoapi/provider/geojson.py:95} WARNING - File s3://my-s3-bucket/path/to/my-data-set.geojson does not exist.
[...]
[2024-11-19T15:59:32Z] {/pygeoapi/pygeoapi/provider/geojson.py:111} WARNING - File s3://my-s3-bucket/path/to/my-data-set.geojson does not exist.
```

These errors refer to source code which is checking local files only:
https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/geojson.py#L82 --> Error thrown in 95
https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/geojson.py#L107 --> Error thrown in 111

Hence, I assume that the GeoJSON provider is not able to handle S3 links, right?

I think that this is related to this PR https://github.com/geopython/pygeoapi/pull/1640.
