### DISCUSSION TITLE
xarray-edr netcdf position query TypeError: |S1 type <class 'numpy.dtypes.BytesDType'> not serializable

### DISCUSSION THREAD

**Discussion by n-o-tud** [geopython/pygeoapi#1961] [Q&A]
Hey,

I'm trying to provide a NetCDF file using xarray-edr to query raster data at a specific position. However, I'm encountering an error with some NetCDF files and am unsure how to troubleshoot it. Below, you'll find a link to the NetCDF file, the corresponding API call, the resulting error, and the configuration file.

How to get rid of the error and make the position query working?

**Link to Netcdf file:** 60 Arc-Second Resolution Bedrock elevation netCDF https://www.ngdc.noaa.gov/thredds/catalog/global/ETOPO2022/60s/60s_bed_elev_netcdf/catalog.html?dataset=globalDatasetScan/ETOPO2022/60s/60s_bed_elev_netcdf/ETOPO_2022_v1_60s_N90W180_bed.nc

**API call:** http://localhost:5000/collections/ETOPO_2022_v1_60s_N90W180_bed_orig/position?f=json&coords=POINT(-75%2045)

**Error:** TypeError: |S1 type <class 'numpy.dtypes.BytesDType'> not serializable

**pygeoapi config:** 
```yaml
 server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    # First language is the default language
    - en-US
    - fr-CA
  # cors: true
  pretty_print: true
  limits:
    default_items: 20
    max_items: 50
  # templates:
  # path: /path/to/Jinja2/templates
  # static: /path/to/static/folder # css/js/img
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  #    manager:
  #        name: TinyDB
  #        connection: /tmp/pygeoapi-process-manager.db
  #        output_dir: /tmp/
  # ogc_schemas_location: /opt/schemas.opengis.net
  admin: false # enable admin api

logging:
  level: DEBUG
  #logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title:
      en: pygeoapi default instance
      fr: instance par défaut de pygeoapi
    description:
      en: pygeoapi provides an API to geospatial data
      fr: pygeoapi fournit une API aux données géospatiales
    keywords:
      en:
        - geospatial
        - data
        - api
      fr:
        - géospatiale
        - données
        - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://example.org
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Organization Name
    url: https://pygeoapi.io
  contact:
    name: Lastname, Firstname
    position: Position Title
    address: Mailing Address
    city: City
    stateorprovince: Administrative Area
    postalcode: Zip or Postal Code
    country: Country
    phone: +xx-xxx-xxx-xxxx
    fax: +xx-xxx-xxx-xxxx
    email: you@example.org
    url: Contact URL
    hours: Mo-Fr 08:00-17:00
    instructions: During hours of service. Off on weekends.
    role: pointOfContact

resources:
  ETOPO_2022_v1_60s_N90W180_bed_orig:
    type: collection
    title: ETOPO Global Relief Model
    description: ETOPO Global Relief Model 60 Arc-Second Resolution Bedrock elevation netCDF
    keywords:
      - observations
      - monitoring
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: 4326
    providers:
      - type: coverage
        name: xarray
        data: tests/data/ETOPO_2022_v1_60s_N90W180_bed_orig.nc
        x_field: lon
        y_field: lat
        storage_crs: 4326
        format:
          name: netcdf
          mimetype: application/x-netcdf
    providers:
      - type: edr
        name: xarray-edr
        data: tests/data/ETOPO_2022_v1_60s_N90W180_bed_orig.nc
        x_field: lon
        y_field: lat
        storage_crs: 4326
        format:
          name: netcdf
          mimetype: application/x-netcdf
```
