### ISSUE TITLE
Error while using PostgreSQL as a source

### ISSUE THREAD

**Issue by krishnaglodha** [geopython/pygeoapi#1040]
**Description**
I'm trying to use postgreSQL table as a data source. Once I put all credentials correct, I'm getting following error on screen
<img width="1379" alt="Screenshot 2022-11-16 at 1 44 55 PM" src="https://user-images.githubusercontent.com/47075664/202125584-d2d510eb-5d37-46ae-a6ee-ec19a28c1f3c.png">

**Steps to Reproduce**
1. Create python venv and install all packages as per `requirements.txt` 
2. Create new data provider using postgreSQL settings 

```
farms: 
        type: collection
        title: Farms
        description: Farm data
        keywords:
            - observations
            - monitoring
        context:
            - datetime: https://schema.org/DateTime
            - vocab: https://example.com/vocab#
              stn_id: "vocab:stn_id"
              value: "vocab:value"
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://www.naturalearthdata.com/
              hreflang: en-US
        providers:
            - type: feature
              name: PostgreSQL
              data:
                  host: localhost
                  port: 5434 # Default 5432 if not provided
                  dbname: postgres
                  user: postgres
                  password: postgres
                  search_path: [public]
              id_field: id
              table: main_farms
              geom_field: geometry
```
**Expected behavior**
I was expecting to see similar demo as we see with other sources
<img width="1325" alt="Screenshot 2022-11-16 at 1 49 01 PM" src="https://user-images.githubusercontent.com/47075664/202125938-a4d4a9e9-2fb5-44ae-95e6-4e3e3022e7cc.png">

**Environment**
 - OS: MAC
 - pygeoapi version: latest
