### ISSUE TITLE
Issue with rendering OGC API Tiles from OS Data Hub vector tiles

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1060]
**Description**
The new functionality in pygeoapi, [enables to use a generic vector tiles endpoint](https://github.com/geopython/pygeoapi/pull/1050) for publishing OGC API - Tiles. In theory this should work with the [OS Vector Tile API](https://osdatahub.os.uk/docs/vts/overview).
However, the preview map does not render the tiles correctly.

**Steps to Reproduce**
Signup at the [OS Data Hub](https://osdatahub.os.uk/), to get an API Key.
Add the data source on the pygeoapi configuration file.:

```
            - type: tile
              name: MVT
              data: https://api.os.uk/maps/vector/v1/vts/boundaries/tile/{z}/{y}/{x}.pbf?srs=3857&key=API-KEY
              options:
                metadata_format: none # default | tilejson
                bounds: [[-180, 90],[-180, 90]]
                zoom:
                    min: 0
                    max: 16
                schemes:
                    - WebMercatorQuad
              format:
                    name: pbf
                    mimetype: application/vnd.mapbox-vector-tile

```

**Expected behavior**
In the Tiles preview, for instance at `http://localhost:5000/collections/os-data-hub/tiles?f=html` a map should render the OS Data Hub Vector Tiles as OGC API Tiles.

**Screenshots/Tracebacks**

The first zoom level shows the tiles correctly placed on the map, but as we zoom in the tiles seemed misplaced.

![os-data-hub1](https://user-images.githubusercontent.com/1038897/205906478-57a7954a-c12b-49ff-8aaf-ec7d2c87b851.png)

![os-data-hub2](https://user-images.githubusercontent.com/1038897/205906512-52b54b20-9cc2-42cb-b8b9-3b979ffafd7a.png)

**Environment**
 - OS: Ubuntu Jammy/ Mac OSX
 - Python version: 3
 - pygeoapi version: 0.14

**Additional context**
Maybe this could be related to the projection, which unlike other examples, is not 4326?
