### ISSUE TITLE
geopackage provider can support custom name for geometry column?

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#1088]
**Is your feature request related to a problem? Please describe.**

When i configure my geopackage with geom_field: 'mygeometry', this is not picked up, the provider expects the columname to be `geom`

In the source i noticed [geom_col](https://github.com/geopython/pygeoapi/blob/f9fb2c600551f2ff11b9e2fb2d3b3aff8c243c98/pygeoapi/provider/sqlite.py#L68), but this is also not picked up

```
  File "/pygeoapi/pygeoapi/provider/sqlite.py", line 298, in query
    row_data = self.cursor.execute(
sqlite3.OperationalError: no such column: geom
```

Other option is to check st_geometry_columns which column(s) are spatial columns in the table

Or does the geopackage spec require the fieldname to be 'geom', in that case [this geopackage](https://service.pdok.nl/bzk/brobhrpvolledigeset/atom/v1_1/downloads/brobhrpvolledigeset.zip) is not optimal

I was able to get this running using the OGR provider:

```
providers:
            -   type: feature
                name: OGR
                data:
                    source_type: GPKG
                    source: /pygeoapi/brobhrpvolledigeset.gpkg
                    gdal_ogr_options:
                        SHPT: POINT
                id_field: bro_id
                layer: borehole_research
```

**Describe the solution you'd like**

support the geom_field property similar to the postgis provider
