### ISSUE TITLE
CRS query parameter support for EDR

### ISSUE THREAD

**Issue by petergarnaes** [geopython/pygeoapi#1104]
Section 8.2.1.4 of the [EDR specification v. 1.0.1](https://docs.ogc.org/is/19-086r5/19-086r5.html) (which is the newest version of writing this) states that a client can specify a `crs` query parameter.

Currently this parameter is not passed to the provider as [this code shows](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/api.py#L3612-L3623), so there is no way to support other CRS than WGS84, because it is the default when not specified

In fact pygeoapi seems to break requirement A.2.12 part C which states that HTTP status code 400 should be returned if CRS is unsupported. If CRS is not passed to the provider, there is no way it can fail if CRS is unsupported. In my testing the `crs` query parameter is completely ignored by pygeoapi for EDR.

**Describe the solution you'd like**
`crs` should be passed to the provider as a query argument and should default to either WGS84 or WGS84h depending on if the Z-axis parameter is specified in either in the `bbox` query argument or `z` query parameter.

The config should also allow specifying supported CRS for the collection, so requirement A.57 can be adhered to.

So config would look something like:
```yml
resources:
  my_collection:
    type: collection
    title: My Collection
    ...
    crs:
     - http://www.opengis.net/def/crs/OGC/1.3/CRS84
     - native
```

There should also be an exception that can be thrown from a provider that results in an HTTP status code 400. Don't know if this is already supported.
