### ISSUE TITLE
Postgres provider doesn't filter the properties defined in config for a collection item

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#1178]
**Description**
When the collection item endpoint is hit the returned feature in GeoJSON has the properties that contains the whole set of fields from the database table even if the properties have been defined in the PG provider configuration of pygeoapi.

**Steps to Reproduce**
Let's imagine we have a table schema with the following fields, no matter what is the type
- uuid
- title
- description
- notes
- geometry

Define a postgres provider like the following:

```yaml
        providers:
            -   type: feature
                name: PostgreSQL
                data:
                    host: 127.0.0.1
                    port: 5432 # Default 5432 if not provided
                    dbname: gis
                    user: pygeoapi
                    password: password
                    search_path: [public]
                properties:
                    - uuid
                    - title
                id_field: uuid
                table: test
                geom_field: geometry
```

**Expected behavior**
Only the `title` property should be returned in the `properties` of the feature when hitting `/collection/items/<uuid>` with the above configuration

**Screenshots/Tracebacks**

**Environment**
 - OS: Mac OS
 - Python version: 3.10.7
 - pygeoapi version: latest

**Additional context**
None
