### ISSUE TITLE
KeyError: 'keywords' on PostgreSQL provider

### ISSUE THREAD

**Issue by kt-manurung** [geopython/pygeoapi#1248]
**Description**
Hi, I've been trying to add a collection from PostgreSQL db, but got KeyError: 'keywords' problem. Can anybody help?

Here is the collection in the example-config.yml:
![image](https://github.com/geopython/pygeoapi/assets/125256434/a21acc09-6d65-4434-ad52-273d1b7b0f90)

**Environment**
 - OS: MacOS Monterey (12.6)
 - Python version: 3.8.11
 - pygeoapi version: 0.15.dev0

![image](https://github.com/geopython/pygeoapi/assets/125256434/dcad4a41-fca8-4ba4-ac19-861f5be93ca9)

**Comment by webb-ben** [comment]
Hi @kt-manurung! This is not an issue with the PostgresSQL provider so much as the configuration. `Keywords` are a required part of the pygeoapi configuration. Something like this should do the trick:
```
test_postgres:
    type: collection
    title:
        en: Test Postgres
    description:
        en: Test Postgres
    keywords:
        en:
            - postgres
            - test
    links:
        - type: text/html
          rel: canonical
          title: Test Information
          href: https://open.canada.ca/en/open-data
          hreflang: en-CA
    extents:
        spatial:
            bbox: [104.889, -8.953, 114.562,-5.628]
            crs: http://www.opengis.net/def/crs/EPSG/0/4326
    providers:
        - type: feature
          name: PostgreSQL
          data:
            host: 127.0.0.1
            port: 5432
            dbname: local_db
            user: postgres 
            password: postgres 
            search_path: [public]
          table: admin_boundary 
          id_field: boundary_id 
          geom_field: geometry
```
For more information, check the [resouces](https://docs.pygeoapi.io/en/latest/configuration.html#resources) section of the pygeoapi docs!
