### ISSUE TITLE
Pydantic v1 is not supported anymore

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#1365]
**Description**
When the latest pygeoapi python package is used as a library in third-party application where there is already a Pydantic dependency pinned at v1 the overall dependencies tree is broken

**Steps to Reproduce**
`poetry update` with `pyproject.toml``
```toml
[tool.poetry.dependencies]
pygeoapi = {git = "https://github.com/geopython/pygeoapi", rev = "master"}
pydantic = "1.10.6"
```

**Expected behavior**
Update is smooth and clean

**Screenshots/Tracebacks**
NA

**Environment**
 - OS: MacOS
 - Python version: 3.9
 - pygeoapi version: master

**Additional context**
NA
