### ISSUE TITLE
Dynamic provider properties

### ISSUE THREAD

**Issue by stefanocudini** [geopython/pygeoapi#1368]
This is useful in cases where I need to generate a large configuration file that I generate in batch way from a data directory.

**Describe the solution you'd like**
In this example of providers I want use the filename as `title_field`
```yaml
providers:
    - type: feature
      name: GeoJSON
      data: tests/alps/lakes.geojson
      id_field: id
      title_field: @filename
```
use a special char(in this examples `@`) for specify a property or methods of resource in this case a file can replaced with `@filename`

```yaml
providers:
    - type: feature
      name: GeoJSON
      data: tests/alps/lakes.geojson
      id_field: @hash[@filename]
      title_field: name
```
a more advanced operation could be to define methods to calculate the value starting from the properties of the resource (see above: calculate a `hash` for example sha256 of the filename or file contents)

Another example of dynamic prop, generate any id from an [UUID](https://it.wikipedia.org/wiki/Universally_unique_identifier) in cases where I do not have the possibility to extract these values from the data(in the example having only `name`)
```yaml
providers:
    - type: feature
      name: GeoJSON
      data: tests/alps/lakes.geojson
      id_field: @uuid
      title_field: name
```
