### ISSUE TITLE
Add Custom CRS option for CSW façade

### ISSUE THREAD

**Issue by maxcollombin** [geopython/pygeoapi#1387]
**Description**
I've tried to integrate the following [CSW service](https://www.geocat.ch/geonetwork/srv/fre/csw?service=CSW&version=2.0.2&request=GetCapabilities) but pygeoapi doesn't seem to support its native projection

**Steps to Reproduce**
Docker Compose configuration with the following configuration for the collection:

```
resources:
    geocat:
        type: collection
        title: Swiss Getmetadata Catalogue
        description: Swiss Getmetadata Catalogue
        keywords:
            - metadata
            - swisstopo
            - geocat
        links:
            - type: text/html
              rel: canonical
              title: geocat
              href: https://www.geocat.ch
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: record
              name: CSWFacade
              data: https://www.geocat.ch/geonetwork/srv/fre/csw
              id_field: identifier
              time_field: datetime
              title_field: title
              crs:
                - http://www.opengis.net/def/crs/OGC/1.3/CRS84
                - http://www.opengis.net/def/crs/EPSG/0/2056
              storage_crs: https://www.opengis.net/def/crs/EPSG/0/2056
```

**Expected behavior**
I expect the leaflet map extent to be consistent with that of the CSW service.

**Screenshots/Tracebacks**

![image](https://github.com/geopython/pygeoapi/assets/93529214/9611cb25-838a-4f52-b950-e1af7dd9a8bc)

**Environment**
 - OS: Windows 10
 - Python version: not applicable (docker configuration)
 - pygeoapi version: 3.3

**Additional context**
It might also be relevant to consider the `ElementSetName=full` parameter in the display of information related to the record (`GetRecordById`) but this should perhaps adressed in another issue.
