### ISSUE TITLE
Elasticsearch provider with basic security

### ISSUE THREAD

**Issue by emiliopardo** [geopython/pygeoapi#1413]
**Is your feature request related to a problem? Please describe.**
I have a elasticsearch cluster with basic security, when I use elasticsearch provider I need to pass user and password. When I configuere without user and password 

```
pygeoapi    |   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
pygeoapi    |     raise HTTPError(http_error_msg, response=self)
pygeoapi    | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:
```

**Describe the solution you'd like**
configure in the elasticsearch provider username an password  for https elastic conections

**Comment by tomkralidis** [comment]
The ES provider `data` value can be set as an RFC1738 URL, i.e.:

```yaml
        providers:
            - type: feature
              name: Elasticsearch
              data: http://USERNAME:PASSWORD@localhost:9200/canada-surface-weather-obs
              id_field: some_id
```

To avoid encoding the credentials directly, you also use environment variables, i.e.:

```yaml
        providers:
            - type: feature
              name: Elasticsearch
              data: http://${USERNAME}:${PASSWORD}@localhost:9200/canada-surface-weather-obs
              id_field: some_id
```

Testing this works locally.  If this works for you, I'll update the [ES provider documentation](https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html#elasticsearch).
