### ISSUE TITLE
Not able to see `itemType` on the collections json for Maps config

### ISSUE THREAD

**Issue by krishnaglodha** [geopython/pygeoapi#1416]
**Description**
`itemType` is missing for the configuration that I have added for `provider` of type **map** 

**Steps to Reproduce**

add following to config yml 
```
airports:
        type: collection
        title: airports of the world
        description: airports of the world
        keywords:
            - airports
            - natural earth
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.naturalearthdata.com/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-20037508.34, -20048966.1,20037508.34, 20048966.1]
                crs: http://www.opengis.net/def/crs/EPSG/0/3857
            temporal:
                begin:
                end: null  # or empty
        providers:
            - type: map
              name: MapScript
              data: /data/airport/air_3857.shp
              options:
                  type: MS_LAYER_POINT
                  layer: airport
                  style: /data/airp.sld
              format:
                  name: png
                  mimetype: image/png
```

**Expected behavior**
Able to see `itemType` in the collection json

**Screenshots/Tracebacks**
<img width="1142" alt="Screenshot 2023-12-06 at 4 56 10 PM" src="https://github.com/geopython/pygeoapi/assets/47075664/7939d18c-3071-459b-b62e-c2bd2b0edbf8">

**Environment**
 - OS: MacOS
 - pygeoapi version: latest
