### ISSUE TITLE
Serving tiles from a url on mvt-tippecanoe is not working

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1506]
**Description**
The [docs](https://docs.pygeoapi.io/en/stable/data-publishing/ogcapi-tiles.html?highlight=tippecanoe#mvt) state that the mvt-tippecanoe provider can serve tiles from a data path on disk, or an url. However, when serving tippecanoe tiles from a url, it is not possible to publish tiles or generate tile metadata in the tilejson specification, 

**Steps to Reproduce**
- Render tippecanoe tiles and place them on a web server or a bucket
- Configure pygeoapi to publish these tiles
```
            - type: tile
              name: MVT-tippecanoe
              data: http://localhost:3000/data/lakes/{z}/{x}/{y}.pbf
              options:
                bounds: [[-124.953634,-16.536406],[109.929807,66.969298]]
                zoom:
                    min: 0
                    max: 11
                schemes:
                    - WorldCRS84Quad
              format: 
                    name: pbf
                    mimetype: application/vnd.mapbox-vector-tile

```
- Retrieve a tile: http://localhost:5000/collections/lakes/tiles/WorldCRS84Quad/0/0/0?f=mvt
- Retrieve metadata in the tilejson format: http://localhost:5000/collections/lakes/tiles/WorldCRS84Quad/metadata?f=tilejson

**Expected behavior**
Both requests should return status code: 200.
