### ISSUE TITLE
Provide a default configuration if none given

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pygeoapi#1512]
It would be nice if pygeoapi would be able to start up without the user having to explicitly provide a configuration file. Pygeoapi would use a default configuration and start as normally. This configuration would likely have no resources at all, but at least the server would be able to start and run without error. Moreover, it would be good if this default configuration was merged with whatever is provided by the user (if anything) - something like this:

```yaml
# file my-pygeoapi-config.yml

# all other config parameters not defined here use their respective
# defaults, as specified in the default pygeoapi config

logging:
  level: DEBUG

resources:
  obs:
    type: collection
            title: Observations
        description: My cool observations
        keywords:
            - observations
            - monitoring
        linked-data:
            context:
                - datetime: https://schema.org/DateTime
                - vocab: https://example.com/vocab#
                  stn_id: "vocab:stn_id"
                  value: "vocab:value"
        links:
            - type: text/csv
              rel: canonical
              title: data
              href: https://github.com/mapserver/mapserver/blob/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
            - type: text/csv
              rel: alternate
              title: data
              href: https://raw.githubusercontent.com/mapserver/mapserver/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2000-10-30T18:24:39Z
                end: 2007-10-30T08:57:29Z
        providers:
            - type: feature
              name: CSV
              data: tests/data/obs.csv
              id_field: id
              geometry:
                  x_field: long
                  y_field: lat

```

In the sample above, even if I only specified values for the `logging` and `resources` config keys, pygeoapi would merge this with its own default configuration and would still be able to run.

**Describe alternatives you've considered**
The alternative of leaving things as they are also works - I think this would be a way to simplify user's configuration files on some use cases.
