### ISSUE TITLE
Error while adding ESRI Feature service

### ISSUE THREAD

**Issue by krishnaglodha** [geopython/pygeoapi#1531]
**Description**
I'm facing an error while creating a new resource with ESRI Feature service as per https://docs.pygeoapi.io/en/stable/data-publishing/ogcapi-features.html#esri-feature-service ,  
my ESRI URL is  https://sampleserver5.arcgisonline.com/arcgis/rest/services/Water_Network/MapServer/8 . The data is in `EPSG:3443`, I tried putting value of `crs` in provider as 3443 as well as `EPSG:3443` , but no luck. 

**Steps to Reproduce**
my resource looks like this 

```
feature:
        type: collection
        title: Covid cases
        description: Coveid data via ESRI
        keywords:
            - observations
            - monitoring
            - points
        links:
            - type: text/csv
              rel: alternate
              title: custom link
              href: https://rottengrapes.tech/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            
        providers:
            - type: feature
              name: ESRI
              data: https://sampleserver5.arcgisonline.com/arcgis/rest/services/Water_Network/MapServer/8
              id_field: objectid
              crs : EPSG:3443 // I tried putting 3443 as well
```

**Screenshots/Tracebacks**

<img width="1317" alt="Screenshot 2024-02-02 at 8 12 00 PM" src="https://github.com/geopython/pygeoapi/assets/47075664/091ccf6d-e375-42a3-9f68-c6293ce788ca">

**Environment**
 - OS: M1
 - pygeoapi version: latest
