### ISSUE TITLE
Restore PostGIS provider for Tiles

### ISSUE THREAD

**Issue by PascalLike** [geopython/pygeoapi#1551]
**Description**
Before the refactor on tiles providers, it was possible to use pg_tileserv and Martin as providers for tiles.

**Steps to Reproduce**
Add a pg_tileserver as tiles provider, for example:

```
   providers:
       - type: tile
         name: MVT 
         data: http://0.0.0.0:7800/public.ne_50m_admin_0_countries/{z}/{x}/{y}.mvt
            options:
              zoom:
                min: 0
                max: 15
             schemes:
                 - WebMercatorQuad
         format:
             name: pbf 
             mimetype: application/vnd.mapbox-vector-tile

``` 

**Expected behavior**
Is no longer possible to define MVT providers, so I would expect the possibility to define something like:

```
   providers:
       - type: tile
         name: MVT-postgis 
         data: http://0.0.0.0:7800/public.ne_50m_admin_0_countries/{z}/{x}/{y}.mvt
            options:
              zoom:
                min: 0
                max: 15
             schemes:
                 - WebMercatorQuad
         format:
             name: pbf 
             mimetype: application/vnd.mapbox-vector-tile

```
And have tiles available in pygeoapi without errors.

**Environment**
 - OS: Ubuntu
 - Python version: 3.10.12
 - pygeoapi version: latest
