### ISSUE TITLE
add actions for CITE testing

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#1576]
Currently, running CITE tests include [running](https://github.com/geopython/pygeoapi/wiki/OGCCompliance) against https://cite.opengeospatial.org or running locally via Docker.

For each approved OGC API standard that has an ETS available, we should add a GitHub Action that deploys the ETS Docker image and runs against a pygeoapi configuration for the given ETS

Current OGC API standards with ETSs:
- [ ] OGC API - Features
- [ ] OGC API - Environmental Data Retrieval
- [ ] OGC API - Processes
- [ ] OGC API - Tiles

**Comment by ricardogsilva** [comment]
@tomkralidis I've started some work on this here:

https://github.com/ricardogsilva/team-engine-action

Still early work, but I'm thinking it would be valuable to contribute it to someplace other than my personal account - perhaps to [geopython](https://github.com/geopython)? or maybe to [opengeospatial](https://github.com/opengeospatial)? I mean after I can get it to a state where it actually works that is :stuck_out_tongue: 

I'm thinking it would be a generic github action, that a user would configure with something like this:

```yaml
jobs:
  perform-cite-testing:
    uses: team-engine-action@some-version
    with:
      server-url: <URL of the server under test>
      test-suites:
        - <id of ETS 1>
        - <id of ETS 2>
        - ...
```
