### ISSUE TITLE
Allow providing a default value in config when env variable does not exist

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pygeoapi#1600]
It would be useful if the pygeoapi config file would allow defining a default value for when an environment variable is not defined.

Something like:

```yaml
        ...
        providers:
            - type: feature
              name: Elasticsearch
              data: ${ELASTICSEARCH_SERVER_URL:-http://localhost:9200}/canada-hydat-daily-mean-02hc003
              id_field: IDENTIFIER
              time_field: DATE

```

In the snippet above, pygeoapi would try to load the `ELASTICSEARCH_SERVER_URL` variable from the environment and in case this variable would not exist, then a default value of `http://localhost:9200` would be used.

**Additional context**
This feature would be useful for me to be able to run, for example the CITE tests in a docker compose stack without having to modify the existing CITE related config file that is present in the tests

I would be willing to provide an implementation for this in a PR if this is deemed a suitable addition
