### ISSUE TITLE
replace base url in config by request header

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#166]
This was a suggestion from @PeaceNlove on gitter.

Replace the hardcoded url configuration by an automated procedure to determine the url from the request headers. In case of existance of X-Forwarded-For header, use that. Should work on reverse proxy's that add this header.

Maybe keep the parameter in config as potential override for special cases where X-Forwarded-For may not be available?

**Comment by justb4** [comment]
Good point! Wanted to suggest already as the current setup makes pygeoapi configs inflexible in deployments (think of DTAP (dutch: OTAP) envs).

Flask/Werkzeug provides all the means to extract the base URL. See for example:

https://stackoverflow.com/questions/15974730/how-do-i-get-the-different-parts-of-a-flask-requests-url and
http://flask.pocoo.org/docs/1.0/deploying/wsgi-standalone/?highlight=proxy#proxy-setups

**Comment by tomkralidis** [comment]
We have since supported environment variables as part of configuration, so something like the following would work:

```yaml
server:
    bind:
        host: ${MY_CUSTOM_HOST_ENV_VAR}
        port: ${MY_CUSTOM_PORT_ENV_VAR}
    url: ${MY_CUSTOM_URL_ENV_VAR}
```

Would/does this help?
