### ISSUE TITLE
Wrong extent/bbox axis-ordering for some collections in Docker pygeoapi config 

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#1702]
**Description**
Three collections (all Dutch data) have reversed axis ordering in spatial extent config.

**Steps to Reproduce**

* start pygeoapi with Docker using default config: `docker run --rm -p 5000:80 geopython/pygeoapi:latest`
* go to any of the Dutch data collections, e.g. http://localhost:5000/collections/ogr_addresses_sqlite
* observe extent somewhere in ocean east of Africa
* when browsing features, the coordinates are ok, it is only the extent

**Expected behavior**
Expected extents within The Netherlands.

**Screenshots/Tracebacks**
![image](https://github.com/geopython/pygeoapi/assets/582630/66833118-45ba-4db2-b513-038507e5d829)

**Environment**
 - Docker 
 - pygeoapi version: latest as on July 1, 2024

**Additional context**
The Docker Image contains:
https://github.com/geopython/pygeoapi/blob/master/docker/default.config.yml
Here, at three location we need to change/reverse the spatial extent defs, for example:

```
        extents:
            spatial:
                bbox: [50.7539, 7.21097, 53.4658, 3.37087]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
```
must become
```
        extents:
            spatial:
                bbox: [7.21097, 50.7539, 3.37087, 53.4658]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
```

as CRS http://www.opengis.net/def/crs/OGC/1.3/CRS84 prescribes lon/lat ordering.
