### ISSUE TITLE
EDR /items Queries Always Routed to OAF Provider

### ISSUE THREAD

**Issue by webb-ben** [geopython/pygeoapi#1748]
**Description**
When executing EDR /items queries, the requests never reach the EDR provider because the /items Flask route always defaults to using an OAF provider instead of the intended EDR provider.

**Steps to Reproduce**

1. Set up a pygeoapi instance with an EDR provider enabling an items query:
```python
    @BaseEDRProvider.register()
    def items(self, **kwargs):
```
2. Execute an /items query against the EDR endpoint.
3. Observe that the query is not processed by the EDR provider but is instead routed to the OGC API - Features provider.

**Expected behavior**
The /items query should be processed by the configured EDR provider, not the Features provider.

**Screenshots/Tracebacks**

**Environment**
 - OS: Linux
 - Python version: 3.10
 - pygeoapi version: 0.18.dev0

**Additional context**
Note I am able to seamless run both an EDR and Features provider by providing configurations for both providers, as such the EDR `/items` links are successfully resolved by the feature provider. @tomkralidis is this the intended behavior for pygeoapi?

```yaml
    providers:
      - type: edr
        name: pygeoapi_plugins.provider.sensorthings_edr.SensorThingsEDRProvider
        data: http://host.docker.internal:8999/FROST-Server/v1.1
      - type: feature
        name: pygeoapi.provider.sensorthings.SensorThingsProvider
        data: http://host.docker.internal:8999/FROST-Server/v1.1/Things
```
