### ISSUE TITLE
Add Support for OGC API - Styles

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1809]
The [OGC API - Styles](https://docs.ogc.org/DRAFTS/20-009.html) *Draft* Standard enables map servers, clients as well as visual style editors, to manage and fetch styles. The styles consist of symbolizing instructions that can be applied by a rendering engine on features and/or coverages. The API implements the conceptual model for style encodings and style metadata.

**Comment by doublebyte1** [comment]
A Draft PR was started here: https://github.com/geopython/pygeoapi/pull/1810

**Comment by tomkralidis** [comment]
As discussed, an initial iteration could be listing/access of styles via `/styles`.  Future iterations would include association of a style to a resource and transaction interfaces.

**Comment by Youssef-Harby** [comment]
Should we add `XML` support in https://github.com/geopython/pygeoapi/blob/master/pygeoapi/api/__init__.py#L81-L101 for SLD ?

**Comment by Youssef-Harby** [comment]
Thanks, @doublebyte1 . I am using the exercise data from https://dive.pygeoapi.io/setup/ (bathingwater-estonia) to generate a very simple style using QGIS for SLD 1.1 and Maputnik for Mapbox GL style.

tests/styles/bathing_water_sources.json:
```json
{
  "version": 8,
  "name": "Empty Style",
  "metadata": {"maputnik:renderer": "mlgljs"},
  "sources": {
    "earth": {
      "type": "raster",
      "tiles": ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],
      "minzoom": 0,
      "maxzoom": 16
    },
    "pygeoapi": {
      "type": "vector",
      "tiles": [
        "https://localhost/collections/bathingwater-estonia/tiles/WebMercatorQuad/{z}/{x}/{y}?f=pbf"
      ],
      "minzoom": 0,
      "maxzoom": 16
    }
  },
  "sprite": "",
  "glyphs": "https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf",
  "layers": [
    {"id": "earth", "type": "raster", "source": "earth"},
    {
      "id": "bathingwaterestonia",
      "type": "circle",
      "source": "pygeoapi",
      "source-layer": "bathingwaterestonia",
      "paint": {"circle-color": "rgba(255, 0, 0, 1)", "circle-radius": 10}
    }
  ],
  "id": "oi0gcaa"
}
```

tests/styles/bathing_water_sources.sld:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" version="1.1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se" xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
  <NamedLayer>
    <se:Name>bathingwater-estonia</se:Name>
    <UserStyle>
      <se:Name>bathingwater-estonia</se:Name>
      <se:FeatureTypeStyle>
        <se:Rule>
          <se:Name>Single symbol</se:Name>
          <se:PointSymbolizer>
            <se:Graphic>
              <se:Mark>
                <se:WellKnownName>star</se:WellKnownName>
                <se:Fill>
                  <se:SvgParameter name="fill">#b80808</se:SvgParameter>
                </se:Fill>
                <se:Stroke>
                  <se:SvgParameter name="stroke">#b80808</se:SvgParameter>
                  <se:SvgParameter name="stroke-width">1</se:SvgParameter>
                </se:Stroke>
              </se:Mark>
              <se:Size>24</se:Size>
            </se:Graphic>
          </se:PointSymbolizer>
          <se:PointSymbolizer>
            <se:Graphic>
              <se:Mark>
                <se:WellKnownName>star</se:WellKnownName>
                <se:Fill>
                  <se:SvgParameter name="fill">#ff0000</se:SvgParameter>
                </se:Fill>
                <se:Stroke>
                  <se:SvgParameter name="stroke">#ff0000</se:SvgParameter>
                  <se:SvgParameter name="stroke-width">1</se:SvgParameter>
                </se:Stroke>
              </se:Mark>
              <se:Size>26</se:Size>
              <se:Rotation>
                <ogc:Literal>34</ogc:Literal>
              </se:Rotation>
            </se:Graphic>
          </se:PointSymbolizer>
        </se:Rule>
      </se:FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
```

Also, I have started working on https://github.com/Youssef-Harby/pygeoapi/tree/styles , incorporating your changes/boilerplate, and began drafting from that point. However, since your plan involves serving only simple SLDs from a directory, I would like to ask if you could provide an example configuration YAML showing how you would prefer the SLD to be defined, so we're aligned on the same page.

**Comment by doublebyte1** [comment]
@Youssef-Harby: sure, based on your example, I was thinking of something like this (but open to feedback!): 😁

```
          bathingwater-estonia:
              type: collection
              title: Bathing water sources
              description: Data of bathing water sources used by water supply systems under the supervision of the Health Board from the Water Health Information System.
              keywords:
                  - Water
                  - Water bodies
                  - Drilled wells
                  - Surface water
                  - Groundwater
                  - Environmental health
                  - Health
                  - Bathing water
              links:
                  - type: text/html
                    rel: canonical
                    title: information
                    href: https://avaandmed.eesti.ee/api/datasets/slug/supluskohad
                    hreflang: en-US
              extents:
                  spatial:
                      bbox:
                          [
                              22.2290936066586440,
                              57.6912449743385451,
                              28.2024877654160555,
                              59.6097269178904412,
                          ]
                      crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
                  temporal:
                      begin: null
                      end: null # or empty
              providers:
                  - type: feature
                    name: GeoJSON
                    data: tests/data/tartu/bathingwater-estonia.geojson
                    id_field: id
                    styles:
                        - name: water-bodies
                          title: Water Bodies SLD Style
                          style:
                              type: sld
                              version: 1.1
                              data: tests/styles/bathing_water_sources.sld
                  - type: tile
                    name: MVT-tippecanoe
                    data: tests/data/tiles_es/ # local directory tree
                    options:
                        zoom:
                            min: 0
                            max: 16
                    format:
                        name: pbf
                        mimetype: application/vnd.mapbox-vector-tile
                  - type: style
                    name: style-file
                    options:
                        format: mbs
                    data: tests/styles/bathing_water_sources.json # local directory tree
```

In summary, the type would be the new type, `style` and we would have to implement one plugin to load the style from a file on disk. Ultimately, this plugin should have as option the style format, but for now, we could even remove the options and just assume a default format (e.g.: mapbox or sld).

**Comment by doublebyte1** [comment]
@tomkralidis what do you think? :-)

**Comment by tomkralidis** [comment]
Catching up here, as @doublebyte1 mentions, we have styles in a couple of contexts.  Below are thoughts on workflows:

1. OGC API - Styles support: this means listing/fetching styles from a repository (default would be filesystem).  We implement this workflow in a similar manner as processes, i.e.:

```yaml
resources:
    my-styles:
        type: style
        provider: pygeoapi.style.filesystem.MyStyleFileSystemProvider
```
2. Any OGC API that can use a style: this means applying a style definition to generation of a map, tile, etc.  In this case, pointing to a style file is fine/safe.  A `styles` array can be used (we can update/normalize in future work w/ maps) to idenitfy 1..n styles in scope.  For large workflows/configurations, YAML anchoring/referencing can be leveraged for reuse.
