### ISSUE TITLE
Add ability for Esri Feature Service provider to work with secured self-hosted service

### ISSUE THREAD

**Issue by colin-geo** [geopython/pygeoapi#1812]
**Problem**
We are using pygeoapi to connect to a client's Esri ArcGIS Server for a feature service that is secured and requires generation of a token by calling their token service endpoint deployed within their self-hosted ArcGIS Portal. The current provider allows for a username and password to be passed in the configuration, however the token is hard-coded to generate from https://www.arcgis.com/sharing/rest/generateToken which results in an error due to the username and password not being valid. Obviously this is because the token is being generated for ArcGIS Online services and not for the self-hosted solution.

**Solution**
Allow the configuration of the provider to specify a custom token service endpoint and a referer value which can be used in conjunction with the username and password to get a token.  Something like:

```
providers:
    - type: feature
      name: ESRI
      data: https://sampleserver5.arcgisonline.com/arcgis/rest/services/NYTimes_Covid19Cases_USCounties/MapServer/0
      id_field: objectid
      time_field: date_in_your_device_time_zone # Optional time field
      crs: 4326 # Optional crs (default is EPSG:4326)
      username: username # Optional username
      password: password # Optional password
      token_service: token_service_url # Optional token service url for self-hosted servers
      referer: referer # Optional referer value to send to token service
```

If the token_service configuration setting is provided then the login code would use that over the hard-coded ArcGIS service url.
