### ISSUE TITLE
Add support to tileindexing in MapScript Provider

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1930]
[Tileindexes](https://mapserver.org/optimization/tileindex.html) are MapServer’s method for doing on-the-fly mosaicing. They are supported in MapScript, and it would be nice to support them also in the MapScript provider.

**Describe the solution you'd like**
I would like to support tileindexes, by introducing a simple boolean parameter `tileindex`.

```
        providers:
          - type: map
            name: MapScript
            data: /data/orto_index_all.shp
            options:
                type: MS_LAYER_RASTER
                tileindex: True
                layer: sample
            format:
                name: png
                mimetype: image/png

```

This parameter should be optional, and default to False (e.g.: no tileindex).

**Describe alternatives you've considered**
The alternative could be remain without tile indexing, and serve different files as different layers. However, that approach is less efficient than having indexing.

**Additional context**
Tile indexes require an index file, that can be generated with [gdalindex](https://gdal.org/en/stable/programs/gdaltindex.html).
