### ISSUE TITLE
support STAC specification

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#221]
Implement the [STAC](https://stacspec.org/) API specification to support search/discovery of geospatial assets.  Notes for implementation based on initial discussions with @matthewhanson :

- add front end routes (`/stac/search`)
- update `pygeoapi.api` to address request handling
- implement STAC provider backend via plugin mechanism which will interrogate backend and return results as a Python dictionary for marshalling to JSON proper to the client
- add stubs for transactional capability
- populating a STAC backend could be via workflow beyond pygeoapi (i.e. implement a CLI within the backend, which is not hooked into pygeoapi tooling proper but can be run offline just the same)

**Comment by pvgenuchten** [comment]
I'm curious to see how stac, ogcapi-coverage and ogcapi-records operate together on a single endpoint, what aspects they can share and where are the challenges, would be good input for the upcoming sprint

**Comment by francbartoli** [comment]
> Implement the [STAC](https://stacspec.org/) API specification to support search/discovery of geospatial assets. Notes for implementation based on initial discussions with @matthewhanson :
> 
> * add front end routes (`/stac/search`)
> * update `pygeoapi.api` to address request handling
> * implement STAC provider backend via plugin mechanism which will interrogate backend and return results as a Python dictionary for marshalling to JSON proper to the client

Are you considering external libraries for marshalling? Or we need to implement our own?

> * add stubs for transactional capability
> * populating a STAC backend could be via workflow beyond pygeoapi (i.e. implement a CLI within the backend, which is not hooked into pygeoapi tooling proper but can be run offline just the same)

**Comment by tomkralidis** [comment]
> Are you considering external libraries for marshalling? Or we need to implement our own?

Good point.  I'm guessing a STAC backend could provided via one of the [sat-utils](https://github.com/sat-utils/sat-stac-landsat) tools (for example) and a STAC backend's mission would be to provide Python `dict`'s of JSON objects back to `pygeoapi.api`, but this remains to be seen/needs to be further tested.

**Comment by francbartoli** [comment]
> > Are you considering external libraries for marshalling? Or we need to implement our own?
> 
> Good point. I'm guessing a STAC backend could provided via one of the [sat-utils](https://github.com/sat-utils/sat-stac-landsat) tools (for example) and a STAC backend's mission would be to provide Python `dict`'s of JSON objects back to `pygeoapi.api`, but this remains to be seen/needs to be further tested.

Ok that makes sense, thanks @tomkralidis.

**Comment by francbartoli** [comment]
@tomkralidis  Should `stac/search` endpoint be optional in the configuration? I would say yes...

**Comment by tomkralidis** [comment]
Would this depend on how we describe in configuration? Like, is STAC a dataset in config?  Other options?

**Comment by pvgenuchten** [comment]
Any guidance from the stac team? Is stac intended to run along side ogc api’s in a single ogc-api endpoint, or does it require it’s own endpoint, in that case maybe deploy a second instance of pygeoapi in a ‘stac’ modus?

**Comment by francbartoli** [comment]
@pvgenuchten I would consider its own endpoint as suggested in the bullet above from @tomkralidis (cc @matthewhanson)

**Comment by francbartoli** [comment]
Configuration could be something like:

```yaml
catalogs:
    sat-api:
        provider:
            name: STAC
            data: https://sat-api-dev.developmentseed.org/stac
```

**Comment by lossyrob** [comment]
@francbartoli is the thought that STAC catalog providers would be their own provider architecture (i.e. separate from dataproviders), or that STAC would be a quality of existing data providers? If an elasticsearch backend, for instance, was loaded with STAC Items (perhaps marked in the `dataset` configuration), then some STAC-specific capabilities could be enabled.

To comment on the above comment:

> Is stac intended to run along side ogc api’s in a single ogc-api endpoint, or does it require it’s own endpoint, in that case maybe deploy a second instance of pygeoapi in a ‘stac’ modus?

My understanding  (which is a bit weaker, since I mostly work with static STACs) is that STAC API contains some [additional endpoints](https://github.com/radiantearth/stac-spec/blob/master/api-spec/api-spec.md#stac-endpoints):

- `/stac` - Simply gets the root catalog.
- `/stac/search` - Implemented so that STAC can do more advanced queries via extensions than what OAF currently supports

The idea would be that eventually, with the  convergence of the Query/Filter extensions into OAF, the second endpoint would go away.

@matthewhanson could provide more info as I'm basically summarizing  what I heard from him yesterday at the STAC sprint.

**Comment by matthewhanson** [comment]
There is currently a PR up to change those endpoints: https://github.com/radiantearth/stac-spec/pull/632

The `/stac` endpoint would go away because it's redundant with the root endpoint `/` - it just returns a STAC catalog, which is the same thing that the root OAF endpoint returns with some additional fields.

`/stac/search` endpoint is proposed to be be renamed to `/items` and proposed to OAF as a general cross-collection search endpoint.  However, this wouldn't go in until OAF 1.1.

**Comment by francbartoli** [comment]
Thanks @matthewhanson, so in the meantime, we could adopt `/items` but for users that might be a bit confusing to understand if it is not part yet of the OAF spec. And we don't know when it will land there

**Comment by matthewhanson** [comment]
Right, not sure when it will land, but now it's agreed it's going to be `/search` not `/items`

**Comment by francbartoli** [comment]
> @francbartoli is the thought that STAC catalog providers would be their own provider architecture (i.e. separate from dataproviders), or that STAC would be a quality of existing data providers? If an elasticsearch backend, for instance, was loaded with STAC Items (perhaps marked in the `dataset` configuration), then some STAC-specific capabilities could be enabled.
> 
@lossyrob do you mean something like this below (looking at earth-search)?

```yaml
datasets:
    cbers4-awfi:
        title: CBERS 4 AWFI Imagery
        description: CBERS 4 AWFI Imagery
        keywords:
            - stac
            - stac-api
            - assets
        links:
                -   type: application/json
                    rel: collection
                    title: information
                    href: https://earth-search.aws.element84.com/collections/cbers4-awfi
                    hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null  # or empty (either means open ended)
        provider:
            name: STAC
            data: # borrow data architecture from OGR provider
                source_type: ES
                source: ES:http://localhost:9200/cbers4-awfi
```

we are then implicitly saying that `cbers4-awfi` is a collection but at some point losing the knowledge of being a specific stac one. I mean at least from an OAPIF perspective.

On the other hand, we could have a dedicated architecture like:

```yaml
catalogues:
    hello-catalogue:
        type: OAPIC (CAT4)???

    sat-api:
        type: STAC
        provider:
            name: STAC
            datasets:
                cbers4-awfi:
                    title: CBERS 4 AWFI Imagery
                    description: CBERS 4 AWFI Imagery
                    keywords:
                        - stac
                        - stac-api
                        - assets
                    links:
                        -   type: application/json
                            rel: collection
                            title: information
                            href: https://earth-search.aws.element84.com/collections/cbers4-awfi
                            hreflang: en-US
                    extents:
                        spatial:
                            bbox: [-180,-90,180,90]
                            crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
                        temporal:
                            begin: null
                            end: null  # or empty (either means open ended)
                    provider:
                        name: STAC
                        data: # borrow data architecture from OGR provider
                            source_type: ES
                            source: ES:http://localhost:9200/cbers4-awfi
```
Here the concept of collection is nested in the specific provider type. Other options @tomkralidis @pvgenuchten ?

> To comment on the above comment:
> 
> > Is stac intended to run along side ogc api’s in a single ogc-api endpoint, or does it require it’s own endpoint, in that case maybe deploy a second instance of pygeoapi in a ‘stac’ modus?
> 
> My understanding (which is a bit weaker, since I mostly work with static STACs) is that STAC API contains some [additional endpoints](https://github.com/radiantearth/stac-spec/blob/master/api-spec/api-spec.md#stac-endpoints):
> 
> * `/stac` - Simply gets the root catalog.
> * `/stac/search` - Implemented so that STAC can do more advanced queries via extensions than what OAF currently supports
> 
> The idea would be that eventually, with the convergence of the Query/Filter extensions into OAF, the second endpoint would go away.
> 
> @matthewhanson could provide more info as I'm basically summarizing what I heard from him yesterday at the STAC sprint.

**Comment by tomkralidis** [comment]
Perhaps `/search` as the cross collection search reuses the provider plugin approach and is specified like:

```yaml
catalogues:
    landsat-aws:
        type: STAC
        title: Landsat 8 AWS catalog
        description: Landsat 8 AWS catalog
        keywords:
            - landsat
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://registry.opendata.aws/landsat-8/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2013-03-18
                end: null  # or empty (either means open ended)
        provider:
            name: Elasticsearch
            data: http://localhost:9200/landsat-aws/FeatureCollection
            id_field: ID
```

and then `/search` can is routed to reuse `pygeoapi.get_collection_items`. In the `/search` case, `collections` is a query parameter.  So we can either consider searching every endpoint in `catalogues` in the config, or having a single catalogue with a required `collection` property that can be queried against.  The former would be tricky as to how to return multi-collection results in a single `FeatureCollection`.

Thoughts?
