### ISSUE TITLE
WFS OGR provider fails with a MULTISURFACE geometry in the response from a backend

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#236]
**Description**
If the target WFS service provides a feature with a geometry like MULTISURFACE then pygeoapi api fails to generate GeoJSON.

**Steps to Reproduce**
Use this configuration provider:

```yaml
provider:
            name: OGR
            data:
                source_type: WFS
                source: WFS:https://geonode.wfp.org/geoserver/wfs
                source_srs: EPSG:4326
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                source_options:
                    OGR_WFS_LOAD_MULTIPLE_LAYER_DEFN: NO
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    CPL_DEBUG: NO
            id_field: iso3
            layer: geonode:csp_iso2_type
```

Call:

`curl -XGET http://localhost/geocore/collections/countries/items/NOR?f=json`

Error is:

```bash
[2019-09-16T21:15:34Z] {/pygeoapi/pygeoapi/provider/ogr.py:315} ERROR - the JSON object must be str, bytes or bytearray, not NoneType
[2019-09-16T21:15:34Z] {/pygeoapi/pygeoapi/api.py:614} ERROR - {'code': 'NotFound', 'description': 'identifier not found'}
```

**Expected behavior**
It is expected a GeoJSON output for the feature called

**Screenshots/Tracebacks**

**Environment**
 - OS:
 - Python version: 3.7.4
 - pygeoapi version: 0.6.0/master

**Additional context**
Workaround is to use JSON output format:

```yaml
provider:
            name: OGR
            data:
                source_type: WFS
                source: WFS:https://geonode.wfp.org/geoserver/wfs?outputformat=json
                source_srs: EPSG:4326
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                source_options:
                    OGR_WFS_LOAD_MULTIPLE_LAYER_DEFN: NO
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    CPL_DEBUG: NO
            id_field: iso3
            layer: geonode:csp_iso2_type
```
