### ISSUE TITLE
extents.temporal null value

### ISSUE THREAD

**Issue by alpha-beta-soup** [geopython/pygeoapi#237]
**Is your feature request related to a problem? Please describe.**

Yes; I'm attempting to add some new functionality into pygeoapi. Part of this includes parsing the configuration YAML in order to read the temporal extents and present them as ISO 8601 strings. However the example YAML configuration in this project uses a literal `None` value in YAML, which is parsed as a string. In other places, there is a comment that says `# or empty`. This means there is a confusion in the representation of null:

```yaml
temporal:
    begin: 2011-11-11
    end: now  # or empty
```

```yaml
temporal:
    begin: None
    end: now  # or empty
```

```yaml
temporal:
    begin: 2000-10-30T18:24:39Z
    end: 2007-10-30T08:57:29Z
```

**Describe the solution you'd like**

To not use a literal `"None"` value in YAML; and rather use `null` or an empty value to represent null (open-ended temporal extent, or undefined).

For example, this template:

```yaml
temporal:
    begin: None
    end: now  # or empty
```

... should be:

```yaml
temporal:
    begin:
    end: now  # or empty
```

Note that the use of `"now"` might be troublesome too, since it's interpretation should be the same as null, and it's ambiguous whether it can be used as a value for `begin` as well. But I don't think it's as bad as the use of the string `"None"`.

**Describe alternatives you've considered**

Parsing the string "None" as a Python NoneType. I don't think this is a clean solution.

**Additional context**

Apologies if this is determined in an upstream standard — if it is, I would appreciate a link to it so I could read about the decision. But I suspect the use of `"None"` in the example configurations in this repository might be an oversight. Perhaps there needs to be some validation performed?
