### ISSUE TITLE
Issue with postgres driver schema configuration option and PostGIS functions

### ISSUE THREAD

**Issue by alpha-beta-soup** [geopython/pygeoapi#269]
**Description**
The PostgreSQL driver configuration currently has a `schema` property allowing you to add a schema to the search path (so your table can be found). However if you set this to anything but `public` (which is the default) then the search path seems to be *constrained to* that schema. This is a problem if your data is under schema `x` but the PostGIS functions (e.g. `ST_AsGeoJSON`) that are called in pygeoapi are still defined in the `public` schema. 

**Steps to Reproduce**
- Have data in a non-`public` schema, but leave the PostGIS functions in the default, `public` schema.
- Create a provider configuration like:

```yaml
       provider:
           name: PostgreSQL
           data:
               host: mycoolhost.co.nz
               dbname: my-db
               user: my-read-user
               password: my-read-user-pw
               port: 1234
               schema: x
           id_field: "@id"
           table: my-table
           context: query
```

- Try and request data

**Expected behavior**

There should be no error.

**Screenshots/Tracebacks**

```
[2019-10-04T01:20:45Z] {/pygeoapi/pygeoapi/provider/postgresql.py:221} ERROR - function st_asgeojson(public.geometry) does not exist
LINE 1: ... "hasSampleRelationship", "isFeatureOfInterestOf",ST_AsGeoJS...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

I can hotfix by appending `public` before the calls to `ST_AsGeoJSON`, e.g.

```python
sql_query = SQL("DECLARE \"geo_cursor\" CURSOR FOR \
 SELECT {0},public.ST_AsGeoJSON({1}) FROM {2}").\
    format(db.columns,
    Identifier('geom'),
    Identifier(self.table))
```

But that's not a proper fix since the PostGIS functions aren't constrained to be in that schema.

Another, slightly cleaner workaround is to declare the provider config like:

```yaml
       provider:
           name: PostgreSQL
           data:
               host: mycoolhost.co.nz
               dbname: my-db
               user: my-read-user
               password: my-read-user-pw
               port: 1234
               schema: public,x
           id_field: "@id"
           table: my-table
           context: query
```

(Note the  `schema: public,x`). This avoids the bug but I presume could have other issues further down the track.
