### ISSUE TITLE
OGR Provider fails to output geojson encoded feature with size bigger than 200MB

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#371]
**Description**
Working with this dataset:

```yaml
countries:
        title: Countries
        description: Admin0 official countries from WFP
        keywords:
            - admin0
            - countries
            - WFP
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://geonode.wfp.org/layers/geonode%3Aglb_bnd_adm0_1
              hreflang: en-EN
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: now  # or empty
        provider:
            name: OGR
            data:
                source_type: WFS
                source: WFS:https://geonode.wfp.org/geoserver/wfs
                source_srs: EPSG:4326
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                source_options:
                    OGR_WFS_LOAD_MULTIPLE_LAYER_DEFN: NO
                open_options:
                    EXPOSE_GML_ID: NO
                    URL: https://geonode.wfp.org/geoserver/wfs?outputformat=json
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    CPL_DEBUG: NO
                    GDAL_HTTP_UNSAFESSL: YES
            id_field: adm0_id
            layer: geonode:glb_bnd_adm0_1
```

some features that have geojson output bigger than the default `OGR_GEOJSON_MAX_OBJ_SIZE=200MB` fail with several error messages like:

```shell
/pygeoapi/pygeoapi/provider/ogr.py:122} ERROR - Error Number: 1, Type: Failure, Msg: GeoJSON object too complex, please see the OGR_GEOJSON_MAX_OBJ_SIZE environment option
```

**Steps to Reproduce**

For example _Indonesia_ with `adm0_id=272`

`curl -XGET http://localhost:5000/collections/countries/items/272`

**Expected behavior**
It is expected the correct geojson payload of the response. This can be mitigated in GDAL version 3.0.2 and above by setting this environment variable:

```shell
OGR_GEOJSON_MAX_OBJ_SIZE=500MB
```

However the error happening in the code is not handled properly

**Screenshots/Tracebacks**

**Environment**
 - OS: Darwin
 - Python version: 3.7.3
 - pygeoapi version: master

**Additional context**
