### ISSUE TITLE
OGR provider for a ESRIJSON driver connection is broken if a feature doesn't have a geometry member

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#390]
**Description**
The ESRIJSON driver from OGR emits errors on connection if the layer has feature without a geometry member.

I'm experiencing this with this covid-19 layer from ArcGIS of JHU:

`https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/2/query?where=objectid+%3D+objectid&f=json&outFields=*`

There is evidence of what causes the error with OGR provider in the following [discussion](http://osgeo-org.1560.x6.nabble.com/gdal-dev-Failure-to-fetch-covid-19-data-from-JHU-ArcGIS-instance-td5434432.html) on the GDAL dev mailing list.

**Steps to Reproduce**
Place this piece of configuration in local.config.yml:

```yml
datasets:
    cases:
        title: Cases for country
        description: Covid-19 cases from JHU
        keywords:
            - admin0
            - countries
            - JHU
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://example.com
              hreflang: en-EN
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: now  # or empty
        provider:
            name: OGR
            data:
                source_type: ESRIJSON
                source: https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&f=json
                source_srs: EPSG:4326
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True

                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: OBJECTID
            layer: ESRIJSON
```

`GET http://localhost/collections/cases/items`

**Expected behavior**
As suggested the issue can be overcame by ignoring the errors when the driver establishes th connection

**Screenshots/Tracebacks**

**Environment**
 - OS: Darwin
 - Python version: 3.7.6
 - pygeoapi version: master

**Additional context**
