### ISSUE TITLE
update configuration to be resource specific

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#393]
As discussed on [Gitter](https://gitter.im/geopython/pygeoapi?at=5e8db6df16f84f0461649cb4), currently we have the following setup for data/process definitions:

```yaml
datasets:
    obs:
       ….
processes:
   hello-world:
      ….
```

We should, instead, consider everything as a resource and introduce a type. Example:

```yaml
resources:
    obs:
        type: vector
        ….
    hello-world:
        type: process
        ….
```

This might be better in the long run as we add support for coverages and metadata, etc.

This would be a breaking change, but pre 1.0 is a great time to iron out things like this.
this is also in line with the ‘resource based architecture’ efforts of APIs in general.
