### ISSUE TITLE
CSV support via the OGR provider

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#409]
**Is your feature request related to a problem? Please describe.**
It would be useful to have CSV supported through OGR via the GDAL [virtual layer](https://gdal.org/drivers/vector/csv.html#vsi-virtual-file-system-api-support) so that we can serve such format directly from cloud storages beyond the native support with CSV provider.  

**Describe the solution you'd like**
Something like this below should work:

```yml
     provider:
            name: OGR
            data:
                source_type: CSV
                source: /vsicurl/https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv
                source_srs: EPSG:4326
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                open_options:
                    X_POSSIBLE_NAMES: long
                    Y_POSSIBLE_NAMES: lat
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: fid
            time_field: data
            layer: dpc-covid19-ita-regioni
```

**Describe alternatives you've considered**
The native CSV provider

**Additional context**
