### ISSUE TITLE
schema for queryables is wrong

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#485]
**Description**

Following the documentation and running the server the `queryables` endpoint for a collection doesn't return the schema as it has been defined in the generated openapi document. 

```yaml
/collections/lakes/queryables:
    get:
      description: lakes of the world, public domain
      operationId: getLakesQueryables
      parameters:
      - *id001
      responses:
        '200':
          $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Features
```

Effectively we have a wrong reference in the generated `example-openapi.yml` as you can see from the snippet above. That should not be a `Features` response

**Steps to Reproduce**

https://docs.pygeoapi.io/en/latest/installation.html#for-developers-and-the-truly-impatient

**Expected behavior**

Everything seems good if we just add the schema locally and reference it:

```yaml
  schemas:
    queryables:
      type: object
      required:
        - queryables
      properties:
        queryables:
          type: array
          items:
            type: object
            required:
            - queryable
            - type
            properties:
              queryable:
                description: the token that may be used in a CQL predicate
                type: string
              title:
                description: a human readable title for the queryable
                type: string
              description:
                description: a human-readable narrative describing the queryable
                type: string
              language:
                description: the language used for the title and description
                type: string
                default:
                  - en
              type:
                description: the data type of the queryable
                type: string
              type-ref:
                description: a reference to the formal definition of the type
                type: string
                format: url
```

**Screenshots/Tracebacks**

**Environment**
 - OS:
 - Python version:
 - pygeoapi version:

**Additional context**
