### ISSUE TITLE
Dataset level limit for `Items` page

### ISSUE THREAD

**Issue by RousseauLambertLP** [geopython/pygeoapi#500]
At the moment, the datasets limit shown in the [items page](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/templates/items.html) is the same for every datasets, because the limit is set in [pygeoapi-config.yml](https://github.com/geopython/pygeoapi/blob/master/pygeoapi-config.yml#L40) at the server level (`server.limit`)

Given the large variety of datasets that can be served through pygeoapi, it would be a nice enhancement if we could set a limit at the dataset level that if present, would overwrite the `server.limit` value for that given dataset.

I would see something like:
```
resources:
    obs:
        type: collection
        title: Observations
        description: My cool observations
        limit: 500
        keywords:
            - observations
            - monitoring
...
```

CC @tomkralidis @alexandreleroux
