### ISSUE TITLE
improve stac-item according to stac spec

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#562]
Current implementation of a STAC item varies quite a bit between the types of resources being crawled. For example for shapefiles the file columns are added as properties

According to [STAC Item Spec](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md) the following aspects would need to be minimally implemented

- a datetime property is required, maybe we can use the file timestamp for this
- the name of the collection of which this resource is part of

In order to facilitate [common metadata fiels](https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#stac-common-metadata), it would be desirable to:
- parse some metadata included in the resource (gpkg_metadata table, xxx.shp.xml file, note that this requires awareness of various metadata formats (DC, iso, esri, ...))
- and/or be able to provide some metadata by placing an additional file in the folder which pygeoapi includes in the stac-item response

An example of such a file {resource-name}.md.yml
```YAML
title: Forest lakes in province of Utrecht
description: This dataset contains all lakes in province
license: https://opendefinition.org/licenses/cc-by/
providers:
  name: Province of Utrecht
  roles: ContactPoint
  url: https://utrecht.nl

```
