### ISSUE TITLE
return relevant translated value as collection/item title/description

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#627]
http://docs.opengeospatial.org/DRAFTS/17-069r4.html#string_i18n describes an approach used in ogcapif to return a translated string as part of the response, it means the backend should (be able to) store the value in multiple languages, but return a single value for a key (collection/title, item/abstract, etc) based on the current response language

it is not clear yet if oapi-common/oapi-records are adopting this approach, but it is the most likely way forward.

For collection configuration we can store the title/abstract as 

```YAML
river:
  type: collection
  title:
    en: rivers
    fr: fleuves
  description:
    en: This dataset has rivers of Ontario
    fr: Cet ensemble de données a des rivières de l'Ontario
```

relates to #626
