### ISSUE TITLE
datetime parsing expect to receive datetime.datetime instance but sometimes it get datetime.date

### ISSUE THREAD

**Issue by keul** [geopython/pygeoapi#659]
**Description**

Code execution at this line fails for me: https://github.com/geopython/pygeoapi/blob/50fcfdf047a4fa73f4437ecf3d9dece4586a8da4/pygeoapi/api.py#L2561

With the following stacktrace:

```
  File "/var/folders/gc/ry76n9m15l7br5j9tnqvy5kc0000gn/T/tmp1Yp0gu/lib/python3.7/site-packages/pygeoapi/api.py", line 2211, in validate_datetime
    if te['begin'] is not None and te['begin'].tzinfo is None:
AttributeError: 'datetime.date' object has no attribute 'tzinfo'
```

**Steps to Reproduce**

This seems generated by our configuration, where we have:

```yaml
# …
        extents:
            spatial:
                bbox: [10,30,30,50]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2014-01-01
                end: 2016-01-01
```

The begin/end spatial as simple date works, but then loading `temporal` in the code above we get simple datetime.date instance.

**Expected behavior**

- do not allow use of `begin` or `end` date as above, or…
- be sure to treat everything as datetime and convert it in case (preferred)

**Environment**
 - OS: MacOS (Google App Engine)
 - Python version: 3.7.10
 - pygeoapi version: 0.9.0

**Comment by tomkralidis** [comment]
@keul thanks for the info.  The temporal values are expected in RFC3339 format (see https://docs.pygeoapi.io/en/latest/configuration.html#resources). Are you able to try with fully qualified datetime values in your configuration?  For example:

```
# …
        extents:
            spatial:
                bbox: [10,30,30,50]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2014-01-01T00:00:00Z
                end: 2016-01-01T00:00:00Z
```
