### ISSUE TITLE
multilingual support in CSV provider

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#663]
This is a suggestion for adding multilingual support to the CSV provider, which can act as a base to other provider implementations.

Goal is to be able to flag which of the CSV fields is the representation of a generic field in a dedicated language. So the CSV provider can return the relevant fields for the requested language

CSV example

id | title_en | title_fr | Englishtext | Frenchtext | x | y
-- | -- | -- | -- | -- | -- | --
1 | flower straat | rue de fleur | a nice street with flowers | belle rue avec des fleurs | 34.3 | 78.2
2 | sea lane | rue de mer | road close to the sea | Route près de la mer | 34.1 | 77.6

## Approach similar to json-ld context embedded in pygeoapi config

pygeoapi could use a json-ld context like configuration to indicate per item property what type, name (definition) and language it has. 

```yaml
fields:
   - id:
       name: @id 
   - title_en: 
        name: schema:name
        lang: en
   - title_fr: 
       name: schema:name
       lang: fr
   - Englishtext:
       name: schema:desc
       lang: en
   - Frenchtext:
       name: schema:desc
       lang: fr
  - x,y:
       name: schema:location
       type: point
       crs: epsg:4326
```

## CSV LD approach 

An alternative approach is to adopt [CSV LD](https://www.w3.org/2013/csvw/wiki/CSV-LD). In this case the pygeoapi config should reference the context file (placed as a sidecar file) which defines a context of and a link to the actual csv file.
