### ISSUE TITLE
Making a coverage request to gdps-temperature with subset fails

### ISSUE THREAD

**Issue by MartinPontius** [geopython/pygeoapi#705]
**Description**
Making a coverage request to the test collection `gdps-temperature` with subset (or bbox) fails.
The problem seems to be in the metadata for this collection in the default config file `pygeoapi-config.yml`. 

By changing `GRIB2` to `GRIB` in the below part of  `pygeoapi-config.yml`, the problem seems to be fixed.

```
        providers:
            - type: coverage
              name: rasterio
              data: tests/data/CMC_glb_TMP_TGL_2_latlon.15x.15_2020081000_P000.grib2
              options:
                  DATA_ENCODING: COMPLEX_PACKING
              format:
                  name: GRIB2
                  mimetype: application/x-grib2
```

**Steps to Reproduce**

1. Follow the installation instructions in the [(documentation)](https://docs.pygeoapi.io/en/latest/installation.html).
2. Make a request: `http://localhost:5000/collections/gdps-temperature/coverage?subset=Lat(40:50),Long(10:20)`

This will produce the following error:

>... rasterio.errors.DriverRegistrationError: ('No such driver registered: %s', b'GRIB2')

**Expected behavior**
Get a response containing the data subset.

**Screenshots/Tracebacks**

**Environment**
 - OS: Ubuntu
 - Python version: Python 3.6.9
 - pygeoapi version: latest commit (4bc929ef876589a50705bf223ec8dec1f5e2a93d), version 0.11.dev0

**Additional context**
I use rasterio version 1.2.2.
