### ISSUE TITLE
Add metadata path property for Tiles provider to config

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#820]
**Is your feature request related to a problem? Please describe.**
I'm trying using pg_tileserv for Vector Tiles, connected to pygeoapi. It's almost there, see above works , but metadata doesn't come through :
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://pg-tileserve-2076-master.kube-idev.bgslcdevops.test/landslides.observation_with_geometry/metadata.json` 

The metadata is at `http://pg-tileserve-2076-master.kube-idev.bgslcdevops.test/landslides.observation_with_geometry.json` but pygeoapi is expecting it at  `http://pg-tileserve-2076-master.kube-idev.bgslcdevops.test/landslides.observation_with_geometry/metadata/landslides.observation_with_geometry.json`

**Describe the solution you'd like**
From Gitter

KoalaGeo @KoalaGeo Nov 10 17:24 - https://gitter.im/geopython/pygeoapi?at=618c005038377967f4a4a2ab
Could I do some sort IF statement at https://github.com/geopython/pygeoapi/blob/8740b23e235c849145c596aac87f61814cf732a0/pygeoapi/provider/mvt.py#L74
For both URL patterns

Francesco Bartoli @francbartoli Nov 10 18:25 - https://gitter.im/geopython/pygeoapi?at=618c0eaad78911028a2f1a25
Yes @KoalaGeo, it’s likely there is a space for improvements there for example when the service is recalling a backend mvt server. Maybe it makes sense to have an additional propetry like a metadata_path in the config file more or less here - https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi_master/local.config.yml#L154 

**Describe alternatives you've considered**
Amend pg_tileserv to change the path it writes the metadata.json

**Comment by KoalaGeo** [comment]
Suggest making the metadata path explicit in the config:

```
providers:
    - type: tile
      name: MVT
      data: tests/data/tiles/ne_110m_lakes  # local directory tree
      # data: https://example.org/ne_110m_lakes/{z}/{x}/{y}.pbf
      metadata: https://example.org/ne_110m_lakes/metadata.json # https://example.org/ne_110m_lakes.json
      options:
          metadata_format: raw # default | tilejson
          bounds: [-7.733181,49.863063,1.763249,60.860926]
          zoom:
              min: 0
              max: 5
          schemes:
              - WebMercatorQuad
              - WorldCRS84Quad
      format:
          name: pbf
          mimetype: application/vnd.mapbox-vector-tile
```
