### ISSUE TITLE
use a column as link with certain 'rel'

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#907]
if one of my columns has a hyperlink to a thumbnail or a link to a related row in another table etc, i would like to move the content of that column from the feature-properties to the link section 

```html
<link rel="alternate" href="http://example.com/collections/foo/items/{column-value}"/>
```
An idea could be to allow to populate https://github.com/geopython/pygeoapi/blob/ce425887d0ff0a17212fa56e264396f8bf3874e0/pygeoapi-config.yml#L162 with a template (see above). Alternatively, we could add a property `link_fields`, like https://github.com/geopython/pygeoapi/blob/ce425887d0ff0a17212fa56e264396f8bf3874e0/pygeoapi-config.yml#L138 and populate it with an array of link fields

```
link-fields:
  - name: thumbnail
    value: "http://example.com/thumbnails/{{thumbnail}}"
    rel: "icon"
```

relates to #906
