### ISSUE TITLE
evaluate yarrrml mappings to represent geojson as json-ld

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#910]
I recently noticed [yarrrml](https://rml.io/yarrrml) as an interesting fit to represent json-flavours such as geojson as rdf/json-ld.

A typical basic yarrrml mapping to represent a geojson in rdf would look like this:

```yaml
prefixes:
 ex: "http://example.com/"

mappings:
  thing:
    sources:
      - ['data.json~jsonpath', '$.features[*]']
    s: ex:$(id)
    po:
      - [a, ex:Thing]
      - [ex:type, $(geometry.type)]
      - [ex:coords, $(geometry.coordinates)]
      - [ex:name, $(properties.name)]
```
the above mapping file would need to be made available for every collection, a default mapping file could transform the basic things.

yarrrml (to-rml) is an npm library and rml is a java library, python alternatives such as https://pypi.org/project/pretty-yarrrml2rml/ seem available though, see a nice user story at https://d2s.semanticscience.org/docs/convert-rml
