### ISSUE TITLE
why are abstract, keywords, links required params on a collection configuration

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#922]
When setting up a new feature collection and skipping the `description`, `keywords` or `links` properties, pygeoapi throws an error that these parameters are required. What is the reason for these params to be required, can't we set a default empty string if not provided?

```yaml
  example:
    type: collection
    title: example
    description: some string
    keywords: some string
    links:
      - type: text/html
         rel: canonical
         title: information
         href: https://opendata.comune.fi.it/
         hreflang: en-US
```
even `title` might not be required, it can take the collection name as default
