### ISSUE TITLE
CC-BY and attribution of a dataset

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#924]
If a CC-BY licensed dataset is published with pygeoapi, I assume we need to capture somewhere the attribution statement. The server has an attribution statement, but this applies to the server, not to a specific dataset.
Can a dataset configuration have an `attribution` property? Is this something which should first be confirmed by OGC API Common, or something we can implement in pygeoapi?

```yaml
example:
        type: collection
        title: example
        description: test test
        keywords: foo
        attribution: Comune di Firenze
```
