### ISSUE TITLE
multilingual collection name

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#956]
with the [multilingual title option for service identification](https://docs.pygeoapi.io/en/latest/language.html#add-translations-for-configurable-text-values), one would expect a similar concept for collection configuration, unfortunately this leads to unexpected behaviour.

```
    firenze-terrains:
        type: collection 
        title: 
            it: Limiti amministrativi comunali ante 2014
            en: Administrative boundaries before 2014
```

<img width="822" alt="image" src="https://user-images.githubusercontent.com/299829/183292173-1df429de-9823-4ca4-a441-252b84e7de2e.png">
