### ISSUE TITLE
Error in the log but everything works as expected

### ISSUE THREAD

**Issue by drnextgis** [geopython/pygeoapi#974]
The relevant part of my configuration file:
```
providers:
    - type: feature
      name: OGR
      data:
          source_type: GPKG
          source: filename.gpkg
      id_field: fid
```

Everything works fine but pygeoapi complains about missing `fid` column when I perform a query:

```
[2022-08-31T20:28:16Z] {/pygeoapi/pygeoapi/provider/ogr.py:477} ERROR - 'fid'
```

```
$ ogrinfo -so filename.gpkg filename | grep fid
FID Column = fid
```

What do you think about replacing `LOGGER.error(err)` with `LOGGER.warning` with probably more explicit message [here](https://github.com/geopython/pygeoapi/blob/c0c2ba541fb4b94b98fbb872915a8bfc62533ecc/pygeoapi/provider/ogr.py#L477)?

**Comment by tomkralidis** [comment]
cc @justb4 

Should this throw an error, given the layer is incorrectly configured?

**Comment by drnextgis** [comment]
@tomkralidis I wouldn't say that the layer is configured incorrectly because I specified the FID field by purpose. Otherwise it raises the following error:
```
[2022-09-04T07:42:39Z] {/pygeoapi/pygeoapi/provider/ogr.py:829} ERROR - Error Number: 1, Type: Failure, Msg: sqlite3_prepare_v2(SELECT Count(*) FROM "lte_rf_hourly_202208151516-decode" WHERE None = '1')
```

**Comment by justb4** [comment]
quick answer: could be corner  case. think 'fid' is a special name in OGR, automatically generated when a collection does not have an id. But indeed the error message should be reconsidered. 
You may want to open the GPKG file with sqlite3 or another sqlite tool to see if there is really a column named 'fid'.

**Comment by drnextgis** [comment]
In my case there is no 'fid' field among normal fields:
```
$ ogrinfo -so filename.gpkg filename      
INFO: Open of `filename.gpkg'
      using driver `GPKG' successful.

Layer name: filename
Geometry: Point
Feature Count: 12853460
Extent: (-127.451000, 14.909000) - (-74.968000, 32.782000)
...
FID Column = fid
Geometry Column = geom
TIMESTAMP: String (0.0)
cell_id: String (0.0)
CELL_NAME: String (0.0)
geohash: String (0.0)
lat: Real (0.0)
lon: Real (0.0)
```
and I want to use FID field as `id_field` which is totally legitimate use case and pygeoapi handles it correctly.

**Comment by tomkralidis** [comment]
@drnextgis can you provide a small test case (data + config)?

**Comment by justb4** [comment]
Had a look and found the following:

If the Layer in the GPKG has a 'fid' column and that column is configured as the `id_field` in pygeoapi, this field is not present in the Layer objects as an explicit OGR Field, but 'internalized' as the FID somehow. Think in some cases there is some magic interrogating the DB.
So 'popping' the id_field in [ogr.py Line 474](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/ogr.py#L474) gives Exception:

```
         try:
             json_feature['id'] = json_feature['properties'].pop(self.id_field)
         except Exception as err:
             LOGGER.error(err)
             json_feature['id'] = ogr_feature.GetFID()
```

We could test for the special case where `id_field` is `fid` but maybe it is better to just leave out the ERROR logging. Maybe a try/catch around the whole as IMHO GeoJSON requires a unique 'id' field (?).

**Comment by justb4** [comment]
"id" is optional in GeoJSON, RFC 7946:
 *If a Feature has a commonly used identifier, that identifier
      SHOULD be included as a member of the Feature object with the name
      "id", and the value of this member is either a JSON string or
      number.*

**Comment by drnextgis** [comment]
> @drnextgis can you provide a small test case (data + config)?

config:
```yaml
server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    test:
        type: collection
        title: filename
        description: description
        links:
            - type: text/csv
              rel: canonical
              title: data
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: OGR
              data:
                  source_type: GPKG
                  source: filename.gpkg
              id_field: fid
              layer: filename
```
data:
[filename.zip](https://github.com/geopython/pygeoapi/files/9485287/filename.zip)

Request example:
```
$ curl -s "http://localhost:5000/collections/test/items/1?f=json&lang=en-US" -H "accept: application/geo+json" | jq
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      -99.216,
      20.014
    ]
  },
  "properties": {
    "geohash": "9g93y72z"
  },
  "id": 1,
  "links": [
    {
      "rel": "self",
      "type": "application/geo+json",
      "title": "This document as GeoJSON",
      "href": "http://localhost:5000/collections/test/items/1?f=json"
    },
    {
      "rel": "alternate",
      "type": "application/ld+json",
      "title": "This document as RDF (JSON-LD)",
      "href": "http://localhost:5000/collections/test/items/1?f=jsonld"
    },
    {
      "rel": "alternate",
      "type": "text/html",
      "title": "This document as HTML",
      "href": "http://localhost:5000/collections/test/items/1?f=html"
    },
    {
      "rel": "collection",
      "type": "application/json",
      "title": "filename",
      "href": "http://localhost:5000/collections/test"
    }
  ]
}
```
```
