### ISSUE TITLE
Error when publishing netcdf file to OGC API - Coverages

### ISSUE THREAD

**Issue by maxcollombin** [geopython/pygeoapi#976]
**Description**
I've been trying to publish a netcdf file to OGC API Coverages as explained [here](https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-coverages.html#publishing-raster-data-to-ogc-api-coverages) but I'm getting the following error:

```
 pygeoapi.provider.base.ProviderConnectionError: [Errno 2] No such file or directory: b'/pygeoapi/data/coads_sst.nc'
```

**Steps to Reproduce**
1. `mkdir pygeoapi/data`
2. `cd pygeoapi/data`
3. Download the file: [coads_sst.nc](https://github.com/geopython/pygeoapi/blob/master/tests/data/coads_sst.nc)
3. `cd ..`
4. `touch docker-compose.yml`
5. Provide the following information in the docker-compose.yml file:
```
version: "3"
services:
  pygeoapi:
    image: geopython/pygeoapi:'0.12.0'
    container_name: pygeoapi
    volumes:
    # local configuration
      - ./local.config.yml:/pygeoapi/local.config.yml 
    # data
      - ./data:/pygeoapi/tests/data
    ports:
      - "5000:80"
```
6. Touch `local.config.yml`
7. Provide service configuration information as specified in the [documentation](https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-coverages.html#publishing-raster-data-to-ogc-api-coverages)
8. Run `docker-compose up -d`

**Expected behavior**

I expect that the container can be properly deployed and that the service can be accessed via the web browser.

**Screenshots/Tracebacks**
- None

**Environment**
 - OS: Windows 10
 - Python version: 3.9.13
 - pygeoapi version: 0.12.0

**Additional context**
- None
