### ISSUE TITLE
Add support for STA CRS conversion

### ISSUE THREAD

**Issue by maxcollombin** [geopython/pygeoapi#977]
**Description**
I've been trying to publish a SensorThings API service but the items are not correctly projected on the map.
EPSG:21781 (CH1903/LV03) is the projection used by the service.

**Steps to Reproduce**
1. `mkdir pygeoapi`
3. `cd pygeoapi`
4. `touch docker-compose.yml`
5. Provide the following information in the docker-compose.yml file:
```
version: "3"
services:
  pygeoapi:
    image: geopython/pygeoapi:'0.12.0'
    container_name: pygeoapi
    volumes:
    # local configuration
      - ./supsi.sta.pygeoapi.config.yml:/pygeoapi/local.config.yml 
    ports:
      - "5000:80"
```
6. Create the file supsi.sta.pygeoapi.config.yml and provide the following information:
```
server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - en-US
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'
logging:
    level: DEBUG
    logfile: /tmp/pygeoapi.log
metadata:
    identification:
        title: 
            en: SensorThings API example endpoint.
        description: Provides STA reference features.
        keywords:
            en:
                - geospatial
                - SensorThingsapi
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/internetofwater/geoconnex.us
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact
resources:
    Things:
        type: collection
        title: SUPSI STA Things
        description: SUPSI SensorThings API Things
        keywords:
            - Things
            - SensorThings
            - IoW
        crs:
            - EPSG:21781
            - EPSG:2056
            - EPSG:4326
            - EPSG:3857
        context:
            - sosa: "http://www.w3.org/ns/sosa/"
              ssn: "http://www.w3.org/ns/ssn/"
              Datastreams: sosa:ObservationCollection
              name: schema:name
        links:
            - type: application/html
              rel: canonical
              title: data source
              href: https://www.supsi.ch/ist
              hreflang: en-US
        extents:
            spatial:
                bbox: [8.382190025288718,45.81795848580136,9.159685205679905,46.63248393787126] 
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84  
            temporal:
                begin: null
                end: null
        providers:
          - type: feature
            name: SensorThings 
            data: https://geoservice2.ist.supsi.ch/indg/frost/v1.1
            source_srs: EPSG:21781
            target_srs: EPSG:4326
            entity: Things 
            intralink: true
            properties:
                - name
                - Datastreams
                - '@iot.selfLink'
```
7. Run `docker-compose up -d`

**Expected behavior**

I expect the items to be correctly reprojected and displayed on the map.

**Screenshots/Tracebacks**
![image](https://user-images.githubusercontent.com/93529214/188165017-8b0ee434-00e8-4b2f-ba7f-cc1b9506edb8.png)
**Environment**
 - OS: Windows 10
 - Python version: 3.9.13
 - pygeoapi version: 0.12.0

**Additional context**
- None
