### ISSUE TITLE
Error while publishing a OA Process through pygeoapi via docker-compose

### ISSUE THREAD

**Issue by maxcollombin** [geopython/pygeoapi#979]
**Description**
I'm tying to publish this [process](https://gist.github.com/maxcollombin/8561c08fc191bce0b3d88cd827637037) through pygeoapi via docker-compose but I'm getting the following error:

```
pygeoapi.plugin.InvalidPluginError: Plugin ZonalStats not found
pygeoapi  | ERROR: openapi.yml could not be generated ERROR
```

**Steps to Reproduce**
1. `svn export https://github.com/geopython/pygeoapi/trunk/docker/examples/simple pygeoapi-simple`
2. `cd pygeoapi-simple`
3. `svn export https://github.com/geopython/pygeoapi/trunk/pygeoapi/process`
4. `svn export https://github.com/geopython/pygeoapi/trunk/pygeoapi/plugin.py`
5. `cd process`
6. add the following [file](https://gist.github.com/maxcollombin/8561c08fc191bce0b3d88cd827637037) to the process folder
7. `cd ..`
8. update the file plugin.py in order the configure the zonalstats process:

```
...
    'process': {
        'HelloWorld': 'pygeoapi.process.hello_world.HelloWorldProcessor'
    },
    'process': {
        'ZonalStats': 'pygeoapi.process.ZonalStats.ZonalStatsProcessor'
    },
...
```
9. update the docker-compose.yml file as follow:

```
version: "3"

services:

  pygeoapi:
    image: geopython/pygeoapi:'0.12.0'
    container_name: pygeoapi
    ports:
      - "5000:80"
    volumes:
      # local configuration
      - ./my.config.yml:/pygeoapi/local.config.yml
      # local process
      - ./process:/pygeoapi/pygeoapi/process
      # local plugin file
      - ./plugin.py:/pygeoapi/pygeoapi/plugin.py
```
10. update the process configuration in the my.config.yml file:

```
...
    # Process # 1:
    hello-world:
        type: process
        processor:
            name: HelloWorld
    # Process # 2:
    zonalstats:
        type: process
        processor:
            name: ZonalStats
```
11. run `docker-compose up -d`

**Expected behavior**
I expected the process to be published and available via the web browser.

**Screenshots/Tracebacks**
- None

**Environment**
 - OS: Windows 10
 - Python version: 3.9.13
 - pygeoapi version: 0.12.0

**Additional context**
- None
